### ISSUE TITLE
Add IEnvironment as second parameter in march/execute to IKonveyorHandler.kt       

### ISSUE THREAD

**Issue by comdiv** [spectrum-project/konveyor#5]
From architecture perspective, `konveyour` **must** provide, and `handler` **could** access some environment. And `handler` **should** use given environment to get current execution's config if it's required.

**Comment by svok** [comment]
Accepted. I will take this in development right after the first pom publication.

**Comment by svok** [comment]
After working some while on IEnvironment I found following peculiarities.
1. IEnvironment is a violation of the Conveyor belt pattern. Parameters other than context must not appear in `exec()` function. All such parameters must go into context.
2. Working with extra parameters is getting too inconvenient since lambdas in Kotlin do not allow default parameters and require to declare all parameters even they are not used like that: `{ _, _ -> }` (if there are more than one parameter). This leads one to have to bear this underscores though all the code.

Thus I recommend not to use `exec(context, environment)` declaration. As a substitution for that I propose to declare an interface on context:
```kotlin
data class MyContext(var x: Int = 0, val env: IKonveyorEnvironment): IEnvKontext {
    override getKonveyorEnv(): IKonveyorEnvironment
}
```

**Comment by comdiv** [comment]
Not agree with it. 
Context should not be constrainted.

We missnamed context and subject.
Subject is an entity that work is applyed to.
Context is an entity that give environment, ruling and state for work.

Clear solution will be go way that Ktor piplines do:

```
interface IKonveyorExecutionContext {
     val environment:IEnvironment
}
interface IKonveyor<T> {
    suspend fun execute (subject:T):Unit
}
interface IKonveyorHandler<T>{
    suspend fun execute(subject:T, context:IKonveyorExecutionContext)
}
```
As it was mentioned in some discussions: Subject (new name for Context) never can be designed to knew anything about Konveyor, while Konveyour should can work with any Subject.
And single Subject could be available for paralell working in different konveyors same time.

**Comment by comdiv** [comment]
And no any problems with lambdas.

You shoud just design DSL that following way:

```
handle(body: (s,c)->Unit) {...}
exec(body:(s)->Unit) = handle{ s,c -> body(s) }
```
So about match and others. We just should go functional-style way in DSL and OOP style while designing core interfaces

**Comment by svok** [comment]
Implemented
